image: node:carbon-jessie

cache:
  paths:
  - node_modules/

stages:
  - build
  # - deploy

build_stage:
  variables:
   DEPLOY_USER: "ubuntu" 
   DEPLOY_URL: "18.213.114.117"
   DEPLOY_DIR: "/var/www/www_cotamos/"
  artifacts:
    paths:
      - dist/  
  stage: build
  script:
   - echo "$DEPLOY_USER"
   - echo "$DEPLOY_URL"
   - echo "$DEPLOY_DIR"
  #  - npm install
  #  - npm run generate
  only:
    refs:
      - master

# deploy_stage:
#   stage: deploy
#   variables:
#    DEPLOY_USER: "ubuntu" 
#    DEPLOY_URL: "18.213.114.117"
#    DEPLOY_DIR: "/var/www/www_cotamos/"
#   before_script:
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#    - 'which zip || ( apt-get update -y && apt-get install zip -y )'
#    - echo "$SSH_KEY" > ssh_key
#    - chmod 400 ssh_key
#    - ssh -i ssh_key -o StrictHostKeyChecking=no ubuntu@18.213.114.117 uptime
#   script:
#    - mv dist/ deploy/
#    - zip -r deploy.zip deploy/*
#    - scp -i ssh_key deploy.zip ubuntu@18.213.114.117:/var/www/www_cotamos/
#    - ssh -i ssh_key ubuntu@18.213.114.117 'unzip -o /var/www/www_cotamos/deploy.zip -d /var/www/www_cotamos'
#    - ssh -i ssh_key ubuntu@18.213.114.117 'cp -rf /var/www/www_cotamos/deploy/* /var/www/www_cotamos/'
#    - ssh -i ssh_key ubuntu@18.213.114.117 'rm /var/www/www_cotamos/deploy.zip'