image: node:carbon-jessie

cache:
  paths:
  - node_modules/
  - dist/

stages:
  - build
  - deploy

build:
  artifacts:
    paths:
      - dist/  
  stage: build
  script:
   - npm install
   - npm run generate
  only:
    refs:
      - dev
      - master
      - homolog

deploy:
  stage: deploy
  variables:
   DEPLOY_USER: "root" 
   DEPLOY_DIR: "/var/www/web-front"
  before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - 'which zip || ( apt-get update -y && apt-get install zip -y )'
   - echo "$SSH_KEY" > ssh_key
   - chmod 400 ssh_key
   - ssh -i ssh_key -o StrictHostKeyChecking=no $DEPLOY_USER@$APP_HOST uptime
  script:
   - mv dist/ deploy/
   - zip -r deploy.zip deploy/*
   - export DEPLOY_DIR="$DEPLOY_DIR/$CI_COMMIT_REF_NAME"
   - ssh -i ssh_key $DEPLOY_USER@$APP_HOST "mkdir -p $DEPLOY_DIR"
   - scp -i ssh_key deploy.zip $DEPLOY_USER@$APP_HOST:$DEPLOY_DIR
   - ssh -i ssh_key $DEPLOY_USER@$APP_HOST "unzip -o $DEPLOY_DIR/deploy.zip -d $DEPLOY_DIR"
   - ssh -i ssh_key $DEPLOY_USER@$APP_HOST "cp -rf $DEPLOY_DIR/deploy/* $DEPLOY_DIR/"
   - ssh -i ssh_key $DEPLOY_USER@$APP_HOST "rm $DEPLOY_DIR/deploy.zip"
  only:
    refs:
      - dev
      - master
      - homolog