image: node:carbon-jessie

cache:
  paths:
  - node_modules/

stages:
  - build
  - deploy

build_stage:
  artifacts:
    paths:
      - dist/  
  stage: build
  script:
   - npm install
   - npm run generate
  only:
    refs:
      - master

deploy_stage:
  stage: deploy
  variables:
   DEPLOY_USER: "ubuntu" 
   DEPLOY_DIR: "/var/www/www_cotamos"
  before_script:
   - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
   - 'which zip || ( apt-get update -y && apt-get install zip -y )'
   - echo "$SSH_KEY" > ssh_key
   - chmod 400 ssh_key
   - ssh -i ssh_key -o StrictHostKeyChecking=no ubuntu@18.213.114.117 uptime
  script:
   - mv dist/ deploy/
   - zip -r deploy.zip deploy/*
   - scp -i ssh_key deploy.zip $DEPLOY_USER@$FRONT_HOST:$DEPLOY_DIR
   - ssh -i ssh_key $DEPLOY_USER@$FRONT_HOST "unzip -o $DEPLOY_DIR/deploy.zip -d $DEPLOY_DIR"
   - ssh -i ssh_key $DEPLOY_USER@$FRONT_HOST "cp -rf $DEPLOY_DIR/deploy/* $DEPLOY_DIR/"
   - ssh -i ssh_key $DEPLOY_USER@$FRONT_HOST "rm $DEPLOY_DIR/deploy.zip"
  #  - ssh -i ssh_key $DEPLOY_USER@$FRONT_HOST 'unzip -o /var/www/www_cotamos/deploy.zip -d /var/www/www_cotamos'
  #  - ssh -i ssh_key $DEPLOY_USER@$FRONT_HOST 'cp -rf /var/www/www_cotamos/deploy/* /var/www/www_cotamos/'
  #  - ssh -i ssh_key $DEPLOY_USER@$FRONT_HOST 'rm /var/www/www_cotamos/deploy.zip'