image: node:carbon-jessie

cache:
  paths:
  - node_modules/
  - dist/

stages:
  - build
  - deploy

build_stage:
  stage: build
  script:
   - npm install
   - npm run generate
  only:
    refs:
      - master

deploy_stage:
  stage: deploy
  script:
   - ls